### ISSUE TITLE
Python3.7 helics extension not working when using Windows installer for HELICS v2.0.0-rc1

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS-src#626]
This is the traceback I get.

```
(py37) C:\local\helics-v2.0.0\python>python
Python 3.7.2 (default, Jan  2 2019, 17:07:39) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import helics
Traceback (most recent call last):
  File "C:\local\helics-v2.0.0\python\helics.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\miniconda3\envs\py37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\local\helics-v2.0.0\python\helics.py", line 17, in <module>
    _helics = swig_import_helper()
  File "C:\local\helics-v2.0.0\python\helics.py", line 16, in swig_import_helper
    return importlib.import_module('_helics')
  File "C:\miniconda3\envs\py37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
>>>
```

I tried the same `import helics` command using Python 3.6 and everything worked fine, so it appears to be an issue specific to Python 3.7.x

**Comment by phlptp** [comment]
Is this going to matter what python version it was built with?  Since I am pretty sure I built the installer using python 3.6 libraries?

**Comment by kdheepak** [comment]
I thought it didn't for different Python 3.x versions, but turns out it does. I'll add a note in the documentation about this.
